# Generated by Django 5.2.16 on 2026-07-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10)),
                ('train_name', models.CharField(max_length=100)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
